spring:
  config:
    import:
      - optional:./mysql-ch-stg.yml

  cloud:
    discovery:
      client:
        simple:
          instances:
            portal-service:
              - uri: http://localhost:8080/core
              - uri: http://127.0.0.1:8080/core

  security:
    debug: true
    oauth2:
      client:
        registration:
          kakao-bizmsg:
            authorization-grant-type: client_credentials
            client-id: R000000071
            client-secret: R000000071_uFkrhKtpTVeca4fZnn2GiA
            scope:
              - read
              - write
          kakao-template:
            authorization-grant-type: client_credentials
            client-id: R000000071
            client-secret: R000000071_uFkrhKtpTVeca4fZnn2GiA
            scope:
              - read
              - write
          kakao-sync:
            authorization-grant-type: authorization_code
            client-id: 5c3a2963a9a33c85427b040b76d55c5b
            client-secret: 5c3a2963a9a33c85427b040b76d55c5b
            redirect-uri: ${KAKAO_SYNC_RETURN_URL:https://kep-talk2.codeclick.co.kr/platform/auth/kakao-sync/authorized}
            scope:
              - read
              - write
        provider:
          kakao-bizmsg:
            token-uri: https://bizmsg-web.kakaoenterprise.com/v1/oauth/token
          kakao-template:
            token-uri: https://bizmsg-web.kakaoenterprise.com/mng/v1/oauth/token
          kakao-sync:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  rabbitmq:
    addresses: 10.0.3.22:5672, 10.0.2.197:5672
    username: ${spring.application.name}
    password: platform!#%135
    connection-timeout: 3600000
    virtual-host: /${spring.application.name}

logging:
  pattern:
    file: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/kep-talk/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    root: info
    com.kep.platform.config.debug.DebugFilter: debug
